### ISSUE TITLE
ipap model doest not support the authenticated-users granting

### ISSUE THREAD

**Issue by anyjack** [sassoftware/sas-viya-authorization-model#2]
HI  ,

I want to use ipap to grant  authenticated-users to one folder  but doesn't OK .   is it support or not? or I missed something?

Thanks in advance for your kindly help.

**Comment by bash-sh** [comment]
Hi @anyjack ,
IPAP currently only works for groups. I'll keep this issue open to include principalType = AuthenticatedUsers in a future release.
Thanks.

**Comment by bash-sh** [comment]
Added the feature to assign permissions to AuthenticatedUsers for both IPAP and DAP.
